name: Tests and coverage
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: NPM install
        run: npm install

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0

      - name: Generate coverage report
        run: npm run test
        continue-on-error: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          verbose: true
